# Generated by Django 2.2.4 on 2020-08-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='project',
            name='invested_by',
        ),
    ]
