# Generated by Django 2.2.4 on 2020-08-27 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200827_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='app.User'),
        ),
        migrations.AlterField(
            model_name='project',
            name='invested_by',
            field=models.ManyToManyField(default='', null=True, related_name='invested_projects', to='app.User'),
        ),
    ]
