# Generated by Django 2.2.4 on 2020-08-27 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200827_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='app.User'),
        ),
        migrations.AlterField(
            model_name='project',
            name='invested_by',
            field=models.ManyToManyField(default='', related_name='invested_projects', to='app.User'),
        ),
    ]
