# Generated by Django 2.2.4 on 2020-08-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200827_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='images/'),
        ),
    ]
