# Generated by Django 2.2.4 on 2020-08-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200827_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='invested_by',
            field=models.ManyToManyField(blank=True, related_name='invested_projects', to='app.User'),
        ),
    ]
